### ISSUE TITLE
[fix] 자잘한 UI 버그 수정

### ISSUE THREAD

**Issue by haeseoklee** [Team-MoMo/MoMo-iOS#120]
<img width="461" alt="스크린샷 2021-01-14 오후 4 52 52" src="https://user-images.githubusercontent.com/20268101/104571345-510fb880-5696-11eb-859d-87c7e315cba8.png">

![스크린샷 2021-01-28 오후 9 45 25](https://user-images.githubusercontent.com/20268101/106140481-2f442480-61b2-11eb-90c8-3716bc4dd98a.png)

- [x] 온보딩에서  로티 아래 section 색이 로티와 다른 문제
- [x] 해양동물 오브제 중 가오리 오브제가 바위보다 아래 있는 문제
- [x] 스플래쉬 시간 3초가 너무 긴 문제
- [x] 첫화면 온보딩 -> 홈 뷰로 바꾸기 (앱잼 데모데이용으로는 온보딩이 항상 먼저 나오게 설정해두었음)

**Comment by jeongchoyi** [comment]
가오리야 눈치챙겨!
