### ISSUE TITLE
[feat] OnboardingMood 구현하기

### ISSUE THREAD

**Issue by haeseoklee** [Team-MoMo/MoMo-iOS#13]
![스크린샷 2021-01-07 오후 1 54 45](https://user-images.githubusercontent.com/20268101/103852758-e8519a80-50ef-11eb-8b74-a3d1cab73728.png)

OnboardingMood, OnboardingSentence 구현하기

**Comment by jeongchoyi** [comment]
요거 각각 뷰 분리해서 이슈 작성하는 건 어떨까용 ?.?

**Comment by haeseoklee** [comment]
@iamcho2 응응 좋은거 같아 너무 많기도 하구

**Comment by haeseoklee** [comment]
@iamcho2 뷰 한개당 이슈 한개씩 생성하는걸로 할까? 지금은 2개씩 묶긴했는데..

**Comment by jeongchoyi** [comment]
난 뷰 한 개씩 이슈 생성이 더 좋은 것 같아! 어차피 commit도 뷰 단위로 할거라면! 각 뷰 별로 브랜치도 파고,, 최대한 세분화ㅎ.ㅎ

**Comment by haeseoklee** [comment]
@iamcho2 오키 바로 반영할게!!
