### ISSUE TITLE
Pull Request 양식

### ISSUE THREAD

**Issue by jeongchoyi** [Team-MoMo/MoMo-iOS#3]
```
### Description
캡쳐 첨부, 한글 설명
### Related Issues
Fixes #이슈번호
```
## 제목
[#이슈번호] 커밋 내용 요약

### Description
캡쳐 첨부, 한글 설명
### Related Issues
Fixes #이슈번호

**Comment by haeseoklee** [comment]
@iamcho2 Wiki에 새로 작성해서 올렸습니다
